jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Run a multi-line script"
      - run: "zip -r app.zip ."
      - name: "Upload S3"
    uses: shallwefootball/upload-s3-action@v1.1.3
    with: 
      aws_bucket: testing-build-sablecloud
      aws_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      source_dir: app.zip
name: CI
true: 
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
