name: Deploy for preview
on: [pull_request]
 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: "Zip application"
      - uses: papeloto/action-zip@v1
      - id: Zip
      with:
        files: .
        recursive: true
        dest: app.zip
      
      - name: "Run a multi-line script"
      - id: Upload
      - uses: actions/checkout@master
        uses: shallwefootball/upload-s3-action@v1.1.3
        with: 
          aws_bucket: testing-build-sablecloud
          aws_key_id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          source_dir: ${{ github.workspace }}/app.zip
