name: Deploy for preview
on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: .
          recursive: true
          dest: tmp/result.zip
      - uses: jakejarvis/s3-sync-action@master
        name: Upload S3
        id: S3
        env:
          AWS_S3_BUCKET: "testing-build-sablecloud"
          SOURCE_DIR: "./tmp/"
          DEST_DIR: ''
